### PR TITLE
Add Catppuccin Colors

### PR DESCRIPTION
**Pull request by Shlok-Bhakta**
## What type of PR is this? (check all applicable)

- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [X] 🎨 Style
- [ ] ♻️ Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert
- [ ] 🌐 Internationalization / Translation

## Description

This adds cappuccin colors to the editor from
https://catppuccin.com/palette

Following the spec as close as I could
https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md

## Related Tickets & Documents

Implements #686

### Monaco
Catppuccin Latte
Monaco L

Catppuccin Frappe
Monaco F

Catppuccin Macchiato
Monaco Ma

Catppuccin Mocha
Monaco Mo

### Codemirror
Catppuccin Latte
Codemirror L

Catppuccin Frappe
Codemirror F

Catppuccin Macchiato
Codemirror Ma

Catppuccin Mocha
Codemirror Mo

### Codejar
Catppuccin Latte
Codejar L

Catppuccin Frappe
Codejar F

Catppuccin Macchiato
Codejar Ma

Catppuccin Mocha
Codejar Mo

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentations?

- [ ] 📓 docs (./docs)
- [ ] 📕 storybook (./storybook)
- [ ] 📜 README.md
- [X] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

None

## [optional] What gif best describes this PR or how it makes you feel?

cat happy

### CODE REVIEW

**Comment by Shlok-Bhakta** [comment]
how do I not duplicate code when adding a theme? @hatemhosny

**Comment by Shlok-Bhakta** [comment]
Themes look good to me! Thank you for fixing my issue!

**Comment by hatemhosny** [comment]
Thank you, @Shlok-Bhakta 
The PR is merged.
You can test it on the development build on: [dev.livecodes.io](https://dev.livecodes.io/)

This will land in [livecodes.io](https://livecodes.io/) in the next release which is planned by the end of this week.
If you have a twitter account, please send it, so that I can give you credit there when the next version is released.
Thanks a lot and you are very welcome to keep contributing to LiveCodes ❤️

**Comment by Shlok-Bhakta** [comment]
Awesome! my twitter is `@shlokbhakta` 

can't wait to use this theme on my blog!

**Pull request merged**
