### PR TITLE
add console message

### PR DESCRIPTION
**Pull request by hatemhosny**
open the browser console ;)

### CODE REVIEW

**Comment by hatemhosny** [comment]
hi @zyf722 

I think this is now ready to merge.
I have added [2 new translation keys](https://github.com/live-codes/livecodes/pull/640/files#diff-8b722c7f80b3937872b013981b7e366566023422874eca20710d1d840e1cc460).

Shall I merge and then start the i18n sync workflow?

**Comment by zyf722** [comment]
> I think this is now ready to merge. I have added [2 new translation keys](https://github.com/live-codes/livecodes/pull/640/files#diff-8b722c7f80b3937872b013981b7e366566023422874eca20710d1d840e1cc460).
> 
> Shall I merge and then start the i18n sync workflow?

Sure, please go ahead - merge the branch, wait for the auto-generated notification and comment `.i18n-update-push` to trigger the push workflow.

If everything goes well, a new branch named `i18n/console-message`will appear both on Github and Lokalise.

**Comment by hatemhosny** [comment]
.i18n-update-push

**Comment by hatemhosny** [comment]
@zyf722 

That worked :)

I added the translations in Lokalize for these 2 keys in different languages.
Shall I pull now?

**Comment by hatemhosny** [comment]
This workflow failed: https://github.com/live-codes/livecodes/actions/runs/11541871404

**Comment by zyf722** [comment]
> This workflow failed: [live-codes/livecodes/actions/runs/11541871404](https://github.com/live-codes/livecodes/actions/runs/11541871404)

I've just fixed this issue and tested it in my fork with [a copy of the i18n project on Lokalise](https://app.lokalise.com/project/60810062671f99b3883fb4.07995509/). Please kindly check the action run [here](https://github.com/zyf722/livecodes/actions/runs/11555842052/job/32162174573) and the related PR [here](https://github.com/zyf722/livecodes/pull/7).

Besides, I've created a new PR to address issues regarding the i18n workflows at #642. Considering that the comment history of #632 is quite long, I suggest we transfer subsequent discussions related to the i18n workflow to this new PR.

Another breaking change introduced in the PR is that `<owner>/<branch>`, instead of just the branch name, is now used for `PR_BRANCH` in CI to avoid potential naming collisions.

For example:
- For this PR merging from `live-codes:console-message` to `live-codes:develop`, the corresponding i18n branch should be `i18n/live-codes/console-message` on both GitHub and Lokalise.
  - ***NOTE***: This also means it is *necessary* to remove the `i18n/console-message` branch previously created on GitHub and Lokalise and re-trigger `.i18n-update-push` so that our tests can run smoothly.
- For gigamaster's UI overhaul PR merging from `gigamaster:dev-gui` to `live-codes:develop`, the corresponding i18n branch should be `i18n/gigamaster/dev-gui`.

However, the default i18n branch `i18n/develop`, which is referenced in `i18n-update-scheduled` (the weekly job to sync between codebase and Lokalise), will still be kept as is to avoid introducing too many breaking changes.

Please feel free to leave comments or ask questions if you have any concerns.

If you think it's ready to continue our testing after merging the fix, please then perform the clean- up mentioned above, re-trigger the push, and translate on Lokalise. After that, we can proceed with testing `i18n-update-pull`. Thanks!

**Comment by hatemhosny** [comment]
.i18n-update-push

**Comment by hatemhosny** [comment]
.i18n-update-pull

**Comment by hatemhosny** [comment]
.i18n-update-push

**Comment by hatemhosny** [comment]
.i18n-update-pull

**Pull request merged**
