### PR TITLE
Code-to-image

### PR DESCRIPTION
**Pull request by hatemhosny**
## What type of PR is this? (check all applicable)

- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] ♻️ Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert
- [ ] 🌐 Internationalization / Translation

## Description

This PR adds a feature of taking screenshots for code and saving it as images

e.g. https://code-to-image.livecodes.pages.dev/?x=id/4dgnt5cs3nb&screen=code-to-image

## Mobile & Desktop Screenshots/Recordings

image

image

image

react_starter

react_starter

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentations?

- [ ] 📓 docs (./docs)
- [ ] 📕 storybook (./storybook)
- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by zyf722** [comment]
It looks great to me!

Just some minor suggestions:

- For me it takes about 1-2 seconds until the browser starts to download the generated image. A progress bar / loading indicator, or simply a mask on the screen, could be added to indicate that the image is being generated.

- Some DOMException shows for `html-to-image` in the console:
image

- It might be more consistent to place the color block inside the rounded-corner input field so that it fits neatly within its borders.
- The `direction` option in the dropdown menu seems to be misplaced. Is it actually the label for the dropdown menu itself?
image

**Comment by hatemhosny** [comment]
Thank you @zyf722 for the valuable comments

> * For me it takes about 1-2 seconds until the browser starts to download the generated image. A progress bar / loading indicator, or simply a mask on the screen, could be added to indicate that the image is being generated.

Added a "Generating..." indicator and the button is displayed as disabled while generating the image.

> * Some DOMException shows for `html-to-image` in the console:

This was a CORS error because of monaco stylesheet (which is not actually used for generating the image!).
Fixed.

> * It might be more consistent to place the color block inside the rounded-corner input field so that it fits neatly within its borders.

Now, the whole field has a consistent rounded border.

> * The `direction` option in the dropdown menu seems to be misplaced. Is it actually the label for the dropdown menu itself?

I'm not sure about this. The text "Direction" is intended to be like a placeholder. It is an option with no value, falling back to the default. I do not want to add an extra label here.

**Comment by hatemhosny** [comment]
hi @gigamaster 

I was glad that applying your design system for the new screen (code-to-image) was straight forward and did not take much effort.
Thank you. You have done a great job indeed.

Please let me know if you have any comments, or if you can come up with better [presets](https://github.com/live-codes/livecodes/blob/65ffdc55ad3d538f511c16a9438847294716703b/src/livecodes/UI/code-to-image.ts#L520-L665).

image

Thank you.

**Comment by hatemhosny** [comment]
.i18n-update-push

**Comment by hatemhosny** [comment]
@zyf722 @gigamaster 

I have added some transperancy for the code block and updated the presets before merging this.
Would you kindly have a look?

I have also added automatic translations on [Lokalise](https://app.lokalise.com/project/34958094667a72e9454592.95108106/?branch=live-codes/code-to-image).

I would appreciate if you can revise the translations. I have already revised the Arabic translation.
Thank you :)

**Comment by zyf722** [comment]
@hatemhosny 

I've just reviewed Simplified Chinese translation and fixed some issues.

Great work! This will be an excellent feature that adds some nice flavor to the application :)

**Comment by hatemhosny** [comment]
Thank you very much @zyf722 
I hope to release this by tomorrow.

**Comment by hatemhosny** [comment]
.i18n-update-pull

**Comment by gigamaster** [comment]
> @zyf722 @gigamaster
> 
> I have added some transperancy for the code block and updated the presets before merging this. Would you kindly have a look?
> 
> I have also added automatic translations on [Lokalise](https://app.lokalise.com/project/34958094667a72e9454592.95108106/?branch=live-codes/code-to-image).
> 
> I would appreciate if you can revise the translations. I have already revised the Arabic translation. Thank you :)

It's a nice feature and it looks great. 
I'm just wondering if it would be possible to switch from capturing the code to capturing the result 
- so as to include a screenshot, a sort of preview, just like on codepen and other showcasing sites.
By the way, I'm traveling and should be back in late January, early February. 
When I'll free up time for opensource and checking translations. 
All the best! Have Fun ^_^/

**Comment by hatemhosny** [comment]
> It's a nice feature and it looks great. I'm just wondering if it would be possible to switch from capturing the code to capturing the result, so as to include a screenshot, a sort of preview, just like on codepen and other showcasing sites. By the way, I'm traveling and should be back in late January, early February. When I'll free up time for opensource and checking translations. All the best! Have Fun ^_^/

@gigamaster 
Lovely to hear from you. I hope you are very well. 

Capturing result previews is indeed a good idea. I have done some work in this direction, but faced some limitations. I will open a new issue for this to discuss it further and explore different options. 

I'm currently working on keyboard shortcuts, and a command menu as discussed in the UI update PR. I'll open a PR soon.

Allow me to mention you in relevant discussions, and please feel free to respond whenever suits you at your convenience when you are back.

Have a safe travel.
Best wishes ❤

**Pull request merged**
