### PR TITLE
Toolbar refinements, neutral colour palette, modal tidy-up

### PR DESCRIPTION
**Pull request by adamgreenough**
## What type of PR is this? (check all applicable)

- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] ♻️ Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

Refines toolbar, particularly spacing of top toolbar buttons, cleaner language tabs
Implements a more neutral colour scheme on dark mode

Completely subjective changes, but I made these amends for myself and thought I would submit for consideration if you preferred this scheme too :)

## Mobile & Desktop Screenshots/Recordings

261697888-07046123-cd14-4d10-b50f-a22776ac5ea2

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentations?

- [ ] 📓 docs (./docs)
- [ ] 📕 storybook (./storybook)
- [ ] 📜 README.md
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by adamgreenough** [comment]
Added some tidy-up to the modals

**Comment by adamgreenough** [comment]
Would be nice to create some more custom prettier designs for the about and welcome modals if you were interested, be happy to help with this :)

**Comment by hatemhosny** [comment]
nice work @adamgreenough 

you definitely have better design skills that I do :)
I will probably get insights from your changes to support custom themes. 
May be we can have a gallery for custom themes that others can use, specially those who have lower design skills like me :)

would you be interested in supplying themes for such a gallery?

**Comment by adamgreenough** [comment]
@hatemhosny Yes absolutely! Sorry for the messy PR, I am still learning to contributing to other repos!

Do you have a project Slack/Discord or anything? I would love to talk about contributing more in the UI department if you were interested :)

**Comment by hatemhosny** [comment]
@adamgreenough 

No problem at all. You are very welcome to contribute.

You may use the [contact page](https://livecodes.io/docs/contact/) for now. I may setup some other form of communication later.

**Pull request closed without merging**
